version: "3.7"
services:
  web:
    build:
      context: .
    ports:
      - "4000:4000"
    env_file:
      - dev.env
    networks:
      - kafka_net

networks:
  kafka_net:
    external: true
    name: kafka_net
